// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kJn8Eel418L8Nl-iG-o-Hbss4n9CVj0',
    appId: '1:249181757153:android:45c84ccd3e6527da6ca1a0',
    messagingSenderId: '249181757153',
    projectId: 'nouvel-air-bb938',
    storageBucket: 'nouvel-air-bb938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47XQBJYQ5_A0FrCuiy2HoktfGmTwdpCc',
    appId: '1:249181757153:ios:49dbd52972e18b636ca1a0',
    messagingSenderId: '249181757153',
    projectId: 'nouvel-air-bb938',
    storageBucket: 'nouvel-air-bb938.appspot.com',
    androidClientId: '249181757153-k121d57r7vrjpmf0golm1i59jh1tvtop.apps.googleusercontent.com',
    iosClientId: '249181757153-0sff5cvm3v2941ojvebtf3qu4spugug7.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.nouvelair',
  );
}
